# Generated by Django 2.1.5 on 2019-06-13 18:07

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20190320_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=256, validators=[shortener.validators.validate_url]),
        ),
    ]
